name: Deploy Laravel Application

on:
  push:
    branches:
      - main  # Change this if you're deploying from another branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Print Secrets
        run: echo "${{ secrets.DIGITALOCEAN_SSH_KEY }}"

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, bcmath, pdo, curl, xml

      - name: Install Composer Dependencies
        run: |
          composer install --no-dev --no-interaction --prefer-dist --optimize-autoloader
          composer dump-autoload

      - name: Install Node.js and Alpine.js Dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install

      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USER }}
          key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
          script: |
            cd /var/www
            sudo chown -R root:root schoolms/
            cd schoolms
            git pull origin main
            cd ..
            sudo chown -R www-data:www-data schoolms/
            cd schoolms
            npm run build
            sudo chown -R www-data:www-data storage bootstrap/cache
            php artisan migrate --force
            php artisan cache:clear
            php artisan config:clear
            php artisan route:clear
            sudo supervisorctl restart laravel-queue:*
